Making it easier to install PerfExpert to a new location. All paths are in a centralized location: perfexpert.properties, which is either in ${HOME}/.perfexpert/ or /opt/apps/perfexpert

diff --git a/perfexpert_run_exp b/perfexpert_run_exp
--- a/perfexpert_run_exp
+++ b/perfexpert_run_exp
@@ -1,12 +1,8 @@
 #!/usr/bin/env bash
 
-# Location of hpcrun, hpcstruct and hpcprof binaries 
-HPCTOOLKIT_BIN=/home/ashay/apps/hpctoolkit/bin
-
 # Event parameters to each run of hpcrun
 # Remove unused experiment lines
 # Each string should be of the format: --event <counter>[:frequency] --event <counter>[:frequency] ...
-
 experiment[0]="--event PAPI_TOT_CYC:13000027 --event PAPI_TOT_INS:13000049 --event PAPI_TLB_DM:510007 --event PAPI_TLB_IM:510031"
 experiment[1]="--event PAPI_TOT_CYC:13000027 --event PAPI_L1_DCA:5300003 --event PAPI_L2_DCA:1300021 --event PAPI_L2_TCM:510007"
 experiment[2]="--event PAPI_TOT_CYC:13000027 --event PAPI_L1_ICA:5300003 --event PAPI_L2_ICA:1300021 --event PAPI_L2_ICM:510007"
@@ -20,6 +16,25 @@ experiment[4]="--event PAPI_TOT_CYC:13000027 --event FP_COMP_OPS_EXE:5300003 --e
 
 #XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#
 #XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#
+
+# Location of hpcrun, hpcstruct and hpcprof binaries 
+main_location="${HOME}/.perfexpert/perfexpert.properties"
+alt_location="/ops/apps/perfexpert/perfexpert.properties";
+
+hpctoolkit_location=`(grep "^HPCTOOLKIT_LOCATION" "${main_location}" | sed -e 's/HPCTOOLKIT_LOCATION[\t ]*=[\t ]*\(.*\)/\1/') 2> /dev/null`
+
+if [ "x${hpctoolkit_location}" == "x" ]
+then
+	# Check the home dir
+	hpctoolkit_location=`(grep "^HPCTOOLKIT_LOCATION" "${alt_location}" | sed -e 's/HPCTOOLKIT_LOCATION[\t ]*=[\t ]*\(.*\)/\1/') 2> /dev/null`
+	if [ "x${hpctoolkit_location}" == "x" ]
+	then
+		echo "Could not find HPCTOOLKIT_LOCATION specified in either \"${main_location}\" or \"${alt_location}\", exiting..."
+		exit 1
+	fi
+fi
+
+HPCTOOLKIT_BIN=${hpctoolkit_location}/bin
 
 # Sanity checks
 if [ ${#} -lt 1 ]
